name: "Post lockfile to future-vuls"
description: "Use this action to automatically create a lockfile in future-vuls."
author: "Marcelo (qwexvf)"
inputs:
  repoName:
    description: "Optional repoName"
    required: false
    default: '1'
outputs:
  pathString:
    description: "Gets full pathString result from the action"
runs:
  using: "docker"
  image: "Dockerfile"
