name: "Post lockfile to future-vuls"
description: "Use this action to automatically create a lockfile in future-vuls."
author: "Marcelo (qwexvf)"
inputs:
  repoName:
    description: "Adds a custom prefix the the beginning of the path."
    required: false
  path:
    description: "Specify path param for a specific lockfile"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
